"""
Authentication Routes
Token validation only - tokens are generated by .NET CRM

This API only VALIDATES tokens that come from your .NET CRM application.
It does NOT generate tokens.
"""

from typing import Optional

from fastapi import APIRouter, Depends
from pydantic import BaseModel

from api.middleware.auth import get_current_user
from api.schemas import UserInfo


router = APIRouter(prefix="/auth", tags=["Authentication"])


class ValidateResponse(BaseModel):
    """Response for token validation"""
    valid: bool
    user: Optional[UserInfo] = None
    message: str


@router.get(
    "/validate",
    response_model=ValidateResponse,
    summary="Validate JWT token",
    description="Validate token from your .NET CRM and get user info"
)
async def validate_token(user: UserInfo = Depends(get_current_user)):
    """
    Validate the JWT token from your .NET CRM.
    
    Send the token in Authorization header: Bearer <token>
    
    Returns user information extracted from the token.
    """
    return ValidateResponse(
        valid=True,
        user=user,
        message="Token is valid"
    )


@router.get(
    "/me",
    response_model=UserInfo,
    summary="Get current user",
    description="Get user information from the JWT token"
)
async def get_me(user: UserInfo = Depends(get_current_user)):
    """Get current user information extracted from JWT token"""
    return user
